<?php $this->headTitle('Master-Bewerbung – Fakultät für Wirtschaftswissenschaften der Uni Regensburg');?>


    <ul class="nav nav-pills" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="deutsch-tab" data-toggle="tab" href="#deutsch" role="tab" aria-controls="deutsch" aria-selected="true">Deutsch</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="english-tab" data-toggle="tab" href="#english" role="tab" aria-controls="english" aria-selected="false">English</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="deutsch" role="tabpanel" aria-labelledby="deutsch-tab">
    <!-- DEUTSCHES TUTORIAL-->
  <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>1</h2>
                </div>
                <div>
                    <b>Allgemeine Informationen</b>
                        <ul>
                            <li>Einsendeschluss ist jeweils der 31. Mai bzw. der 31. November</li> 
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/honors/" target="_blank">Honors-Bewerbungen</a> sind hier ebenfalls m&ouml;glich</li>
                            <li>Es können vorab <b>keine</b> Angaben zu eingegangenen Bewerbungen gemacht werden</li>
                        </ul>
                    <p><b>Links</b>
                        <ul>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/service/studienberatung/faqs/index.html" target="_blank">FAQ</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/" target="_blank">Wirtschaftswissenschaftliche Fakult&auml;t</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/studium/pruefungsordnungen/bachelor/wirtschaftswissenschaften/index.html"target="_blank">Pr&uuml;fungsordnung</a></li>
                            <li><a href="<?php echo $this->URL;?>http://wiwi-app.uni-regensburg.de/studiendekan/AblaufMasterBeurteilung.php"target="_blank">Zulassungsverfahren</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/service/studienberatung/"target="_blank">Studienberatung</a></li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>2</h2>
                </div>
                <div>
                    <p>W&auml;hlen Sie in der oberen Men&uuml;leiste den Link <b>"Bewerbung starten"</b> aus.</p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 2: Login" src="<?php echo $this->base;?>/img/screenshot_bewerbung_starten.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>3</h2>
                </div>
                <div>
                    <p>Wenn Sie eine bestehende Bewerbung mit Ihrem Bewerbungscode aufrufen wollen geben Sie Ihren Bewerbungscode (siehe E-Mail) ein und klicken Sie auf <b>"Bewerbung aufrufen"</b></p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 3: Bewerbungscode aufrufen" src="<?php echo $this->base;?>/img/screenshot_bewerbungscode.png">
                    </p>
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>4</h2>
                </div>
                <div>
                    <p style="margin-bottom:0px;">Im Bewerbungsablauf m&uuml;ssen Sie folgende Anlagen hochladen</p>
                    <ul style="margin-bottom: -3px; margin-top:4px;">
                        <li>Tabellarischen Lebenslauf</li>
                        <li>Alle im Lebenslauf referenzierten Nachweise</li>
                        <li>Notenbescheinigungen (aktuelle Noten&uuml;bersicht bzw. Abschlusszeugnis)</li>
                    </ul>
                    <img style="max-width: 100%; height: auto;"alt="Schritt 4: Anlagen hochladen" src="<?php echo $this->base;?>/img/screenshot_anlage_hochladen.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>5</h2>
                </div>
                <div>
                    <p style="margin-bottom:0px;">Bewerber, deren Hochschulzugangsberechtigung (z.B. Abitur) <b>nicht</b> in Deutschland ausgestellt wurde, müssen dazu auch</p>
                    <ul style="margin-bottom: 0px; margin-top:4px;">
                        <li>Reisepass hochladen</li>
                        <li><a href="http://www.uni-regensburg.de/international/internationale-studierende/medien/finanzierungserklaerung_aktuell.pdf" target="_blank">Finanzierungserkl&auml;rung</a> hochladen</li>
                        <li><a href="http://www.uni-regensburg.de/international/internationale-studierende/medien/dokumente/zulassungsantrag_dt_2_13.pdf" target="_blank">Aufnahmeantrag</a> hochladen</li>
                        <li>ggf.<a href="https://www.hrk.de/fileadmin/redaktion/hrk/02-Dokumente/02-07-Internationales/02-07-04-Hochschulzugang/APS_VereinfVerf2006.pdf" target="_blank"> APS-Zertifikat</a> hochladen</li>
                        <li>Nachweise f&uuml;r Sprachkurse hochladen</li>
                        <li>Zus&auml;tzliche Informationen zu belegten F&auml;chern eintragen</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>6</h2>
                </div>
                <div>
                    <p>Wenn Sie Ihre Daten eingegeben haben klicken Sie am Ende auf den Button <b>"Daten speichern"</b>.</p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 6: Daten eingeben" src="<?php echo $this->base;?>/img/screenshot_daten_speichern.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>7</h2>
                </div>
                <div>
                    <p>Falls Ihnen bei der Eingabe ein Fehler unterlaufen ist klicken Sie auf <b>"Angaben korrigieren"</b></p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 7: Angaben korrigieren" src="<?php echo $this->base;?>/img/screenshot_angaben_korrigieren.png">
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>8</h2>
                </div>
                <div>
                    <p>Wenn alle Angaben korrekt eingegeben und Ihre Unterlagen vollst&auml;ndig sind: Den Button <b>"Bewerbung endg&uuml;ltig absenden"</b> klicken</p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 8: Bewerbung absenden" src="<?php echo $this->base;?>/img/screenshot_bewerbung_absenden.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>9</h2>
                </div>
                <div>
                    <p style="margin-bottom:4px;">Zusammenfassung ausdrucken und postalisch versenden / faxen (Email <b>NICHT</b> zul&auml;ssig)</p>
                    <i style="font-size:14px">
								Universit&auml;t Regensburg<br />
								Fakult&auml;t f&uuml;r Wirtschaftswissenschaften<br />
								Dekanat, Stichwort: Master-Bewerbung<br />
								Universit&auml;tsstrasse 31<br style="margin-bottom:8px;" />
								D-93053 Regensburg<br style="margin-bottom:8px;" />
								<b>Fax: 0941 943 812747</b>
								</i></div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>10</h2>
                </div>
                <div>
                    <p>Bewerber, deren Hochschulzugangsberechtigung <b>nicht</b> in Deutschland ausgestellt wurde (vgl. 5.)</p>
                    <i>S&auml;mtliche Bewerbungsunterlagen inkl. der Zusammenfassung ebenfalls per Post versenden</i><br/><br/> Weitere Informationen erhalten Sie vom <br/><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/international/"target"_blank">International Office</a>
                </div>
            </div>
        </div>
    </div>
  </div>
  <div class="tab-pane fade" id="english" role="tabpanel" aria-labelledby="english-tab">
    <!-- ENGLISCHES TUTORIAL-->
  <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>1</h2>
                </div>
                <div>
                    <b>General information</b>
                        <ul>
                            <li>deadline is the 31. of May respective   ly the 31. of November</li> 
                            <li>It is also possible to apply for <a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/honors/" target="_blank">Honors</a></li>
                            <li><b>No information</b> can be provided in advance.</li>
                        </ul>
                    <p><b>Links</b>
                        <ul>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/service/studienberatung/faqs/index.html" target="_blank">FAQ</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/" target="_blank">Faculty of Business Administration</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/studium/pruefungsordnungen/bachelor/wirtschaftswissenschaften/index.html"target="_blank">examination regulations</a></li>
                            <li><a href="<?php echo $this->URL;?>http://wiwi-app.uni-regensburg.de/studiendekan/AblaufMasterBeurteilung.php"target="_blank">application procedures</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/service/studienberatung/"target="_blank">Student counseling</a></li>
                            <li><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/international/"target"_blank">International Office</a></li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>2</h2>
                </div>
                <div>
                    <p>To start the application: click on the link <b>"Bewerbung starten"</b> in the upper navigationbar.</p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 2: Login" src="<?php echo $this->base;?>/img/screenshot_bewerbung_starten.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>3</h2>
                </div>
                <div>
                    <p> If you want to access an application with your application code, enter it and click on <b>"Bewerbung aufrufen"</b></p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 3: Bewerbungscode aufrufen" src="<?php echo $this->base;?>/img/screenshot_bewerbungscode.png">
                    </p>
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>4</h2>
                </div>
                <div>
                    <p style="margin-bottom:0px;">The following attachments have to be uploaded during the application process</p>
                    <ul style="margin-bottom: -3px; margin-top:4px;">
                        <li>Tabellarischen Lebenslauf</li>
                        <li>Alle im Lebenslauf referenzierten Nachweise</li>
                        <li>Notenbescheinigungen (aktuelle Noten&uuml;bersicht bzw. Abschlusszeugnis)</li>
                    </ul>
                    <img style="max-width: 100%; height: auto;"alt="Schritt 4: Anlagen hochladen" src="<?php echo $this->base;?>/img/screenshot_anlage_hochladen.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>5</h2>
                </div>
                <div>
                    <p style="margin-bottom:0px;">If your university entrance certificate (e.g. A-Levels) is <b>not</b> issued in germany, you must also upload your:</p>
                    <ul style="margin-bottom: 0px; margin-top:4px;">
                        <li>passport</li>
                        <li><a href="http://www.uni-regensburg.de/international/internationale-studierende/medien/finanzierungserklaerung_aktuell.pdf" target="_blank">financing declaration</a></li>
                        <li><a href="http://www.uni-regensburg.de/international/internationale-studierende/medien/dokumente/zulassungsantrag_dt_2_13.pdf" target="_blank">application for admission</a></li>
                        <li>ggf.<a href="https://www.hrk.de/fileadmin/redaktion/hrk/02-Dokumente/02-07-Internationales/02-07-04-Hochschulzugang/APS_VereinfVerf2006.pdf" target="_blank"> APS-certificate</a></li>
                        <li>certificates for language courses</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>6</h2>
                </div>
                <div>
                    <p>If you finished entering your data, click the button <b>"Daten speichern"</b>.</p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 6: Daten eingeben" src="<?php echo $this->base;?>/img/screenshot_daten_speichern.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>7</h2>
                </div>
                <div>
                    <p>If you made some mistakes entering your data, click the button <b>"Angaben korrigieren"</b></p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 7: Angaben korrigieren" src="<?php echo $this->base;?>/img/screenshot_angaben_korrigieren.png">
                </div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>8</h2>
                </div>
                <div>
                    <p>If all data are correct and your documents are complete, click the button <b>"Bewerbung endg&uuml;ltig absenden"</b></p>
                    <img style="max-width: 100%; height: auto;" alt="Schritt 8: Bewerbung absenden" src="<?php echo $this->base;?>/img/screenshot_bewerbung_absenden.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>9</h2>
                </div>
                <div>
                    <p style="margin-bottom:4px;">Print the summary and send it postal or fax it <br/>(Email <b>IS NOT</b> valid)</p>
                    <i style="font-size:14px">
								Universit&auml;t Regensburg<br />
								Fakult&auml;t f&uuml;r Wirtschaftswissenschaften<br />
								Dekanat, Stichwort: Master-Bewerbung<br />
								Universit&auml;tsstrasse 31<br style="margin-bottom:8px;" />
								D-93053 Regensburg<br style="margin-bottom:8px;" />
								<b>Fax: 0941 943 812747</b>
								</i></div>
            </div>
        </div>
        <div class="card col-md-5 col-sm-12 m-2 box">
            <div class="card-body">
                <div class="card-title">
                    <h2>10</h2>
                </div>
                <div>
                    <p>If your university entrance certificate (e.g. A-Levels) is <b>not</b> issued in germany (compare 5.)</p>
                    <i>Send the complete documents inclusive the summary also postal.</i>
                    <br/><br/> For more information consult the <br/><a href="<?php echo $this->URL;?>http://www.uni-regensburg.de/international/"target"_blank">International Office</a>
                </div>
            </div>
        </div>
    </div>
  </div>
  </div>
  </div>
</div>

</body>

    </html>
