<?php
$title1 = 'Bewerbung für Masterstudiengang';
$this->headTitle($title1);

$title2 = 'Persönliche Daten ';
$this->headTitle($title2);

$title3 = 'Angaben zum Werdegang';
$this->headTitle($title3);

$title4 = 'Einschätzung zur Zulassungsvoraussetzung';
$this->headTitle($title4);

$title5 = 'Angaben zur Berufserfahrung';
$this->headTitle($title5);
?>
<div class="jumbotron">
    <b>Information</b><br/>
    Sie k&ouml;nnen durch Anmeldung mit Ihrem pers&ouml;nlichen Bewerbungscode noch bis zum <?php echo $this->bewerbungsFrist ?>
    Ihre Bewerbung &auml;ndern.<br/>
    Sobald Sie Ihre Bewerbung jedoch endg&uuml;ltig abgeschickt haben, sind keine &Auml;nderungen mehr m&ouml;glich.<br/>
    Sie k&ouml;nnen dann nur noch die PDF-Datei mit der Zusammenfassung Ihrer Bewerbung herunterladen, um diese zu unterschreiben
    und an das Dekanat zu senden.

    <p>Ihr Bewerbungscode:<kbd id="bcode" data-clipboard-target="#bcode" style ="cursor: pointer;"><?php echo $this->idBewerbungscode;?></kbd></p>
    <p>
        <b>Daten eingeben</b><br/>
        Bitte f&uuml;llen Sie das Bewerbungsformular aus. In den n&auml;chsten Schritten werden Sie gebeten, die entsprechenden Angaben einzutragen.<br/>
        Am Ende k&ouml;nnen Sie Ihre individuellen Bewerbungsunterladen hochladen und zu Ihrer Bewerbung hinzuf&uuml;gen.
    </p>
</div>


<!-- Studiendaten -->
<div class="card-deck">
	<div class="card">
		<h3 class="card-header" style="font-weight:bold"><?= $this->escapeHtml($title1) ?></h3>
		 <div class="card-body">
			<?php
			$idSemester = $form->get('idSemester');			
			$kuerzelStudiengang = $form->get('kuerzelStudiengang');

			echo $this->form()->openTag($form);
			?>

	<div class="form-row">
		<div class="form-group col">
		    <?= $this->formLabel($idSemester) ?>
		    <?= $this->formElement($idSemester) ?>
		    <?= $this->formElementErrors()->render($idSemester, ['class' => 'help-block']) ?>
		</div>
		<div class="form-group col">
		    <?= $this->formLabel($kuerzelStudiengang) ?>
		    <?= $this->formElement($kuerzelStudiengang) ?>
		    <?= $this->formElementErrors()->render($kuerzelStudiengang, ['class' => 'help-block']) ?>
		     <small class="text-muted">Weitere Informationen zu den Honors-Studiengängen finden Sie auf <a href="http://www.honors.de" target="_blank">www.honors.de</a></small>
	    	</div>
	</div>

 <br>
		
<!-- Persönliche Daten -->
<div class="card-deck">
	<div class="card">
		<h3 class="card-header" style="font-weight:bold"><?= $this->escapeHtml($title2) ?></h3>
		<div class="card-body">
			<?php
			$geschlecht = $form->get('geschlecht');
			$geburtsdatum = $form->get('geburtsdatum');
			$vorname = $form->get('vorname');
			$nachname = $form->get('nachname');
			$strasse = $form->get('strasse');
			$hausnummer = $form->get('hausnummer');
			$plz = $form->get('plz');
			$ort = $form->get('ort');
			$idLand = $form->get('idLand');
			$email = $form->get('email');
			
			$submit = $form->get('submit');
			$form->prepare();

			echo $this->form()->openTag($form);
			?>

			<div class="form-group">
			    <?= $this->formLabel($geschlecht) ?>
			    <?= $this->formElement($geschlecht) ?>
			    <?= $this->formElementErrors()->render($geschlecht, ['class' => 'help-block']) ?>
			</div>

			
			<div class="form-row">
				<div class="form-group col">
				    <?= $this->formLabel($vorname) ?>
				    <?= $this->formElement($vorname) ?>
				    <?= $this->formElementErrors()->render($vorname, ['class' => 'help-block']) ?>
				</div>
				<div class="form-group col">
				    <?= $this->formLabel($nachname) ?>
				    <?= $this->formElement($nachname) ?>
				    <?= $this->formElementErrors()->render($nachname, ['class' => 'help-block']) ?>
			    	</div>
			</div>
		
			<div class="form-group">
			    <?= $this->formLabel($strasse) ?>
			    <?= $this->formElement($strasse) ?>
			    <?= $this->formElementErrors()->render($strasse, ['class' => 'help-block']) ?>
			</div>
			
			<div class="form-row">
				<div class="form-group col">
				    <?= $this->formLabel($hausnummer) ?>
				    <?= $this->formElement($hausnummer) ?>
				    <?= $this->formElementErrors()->render($hausnummer, ['class' => 'help-block']) ?>
				</div>

				<div class="form-group col">
				    <?= $this->formLabel($plz) ?>
				    <?= $this->formElement($plz) ?>
				    <?= $this->formElementErrors()->render($plz, ['class' => 'help-block']) ?>
				</div>
			</div>
			
			<div class="form-row">
				<div class="form-group col">
				    <?= $this->formLabel($ort) ?>
				    <?= $this->formElement($ort) ?>
				    <?= $this->formElementErrors()->render($ort, ['class' => 'help-block']) ?>
				</div>
				<div class="form-group col">
				    <?= $this->formLabel($idLand) ?>
				    <?= $this->formElement($idLand) ?>
				    <?= $this->formElementErrors()->render($idLand, ['class' => 'help-block']) ?>
			    	</div>
			</div>
			
			<div class="form-group">
			    <?= $this->formLabel($geburtsdatum) ?>
			    <?= $this->formElement($geburtsdatum) ?>
			    <?= $this->formElementErrors()->render($geburtsdatum, ['class' => 'help-block']) ?>
			    <small class="text-muted"> Eingabeformat: TT.MM.JJJJ</small>
			</div>

			<div class="form-group">
			    <?= $this->formLabel($email) ?>
			    <?= $this->formElement($email) ?>
			    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
			    <small class="text-muted">Sie werden über das Ergebnis Ihrer Bewerbung per E-Mail informiert.</small>
			</div>
		</div>
	</div>
</div> <br>

<!-- Werdegang -->
<div class="card-deck">
	<div class="card">
		<h3 class="card-header" style="font-weight:bold"><?= $this->escapeHtml($title3) ?></h3>
		<div class="card-body">
			<?php
			$letzteHochschule = $form->get('letzteHochschule');
			$letzteHochschulart = $form->get('letzteHochschulart');
			$studiengang = $form->get('studiengang');
			$abschluss = $form->get('abschluss');
			$abschlussnote = $form->get('abschlussnote');
			$hinweise = $form->get('hinweise');
			?>
			<div class="form-group">
			    <?= $this->formLabel($letzteHochschule) ?>
			    <?= $this->formElement($letzteHochschule) ?>
			    <?= $this->formElementErrors()->render($letzteHochschule, ['class' => 'help-block']) ?>
			    <small class="text-muted">Tragen Sie bitte Ihren aktuellen Studienort ein (z.B. Regensburg).</small>
			</div>

			<div class="form-group">
			    <?= $this->formLabel($letzteHochschulart) ?>
			    <?= $this->formElement($letzteHochschulart) ?>
			    <?= $this->formElementErrors()->render($letzteHochschulart, ['class' => 'help-block']) ?>
			    <small class="text-muted">Tragen Sie bitte Ihre aktuelle Hochschulart ein.</small>
			</div>

			<div class="form-group">
			    <?= $this->formLabel($studiengang) ?>
			    <?= $this->formElement($studiengang) ?>
			    <?= $this->formElementErrors()->render($studiengang, ['class' => 'help-block']) ?>
			    <small class="text-muted">Tragen Sie bitte Ihren aktuellen Studiengang ein (z.B. Betriebswirtschaftslehre).</small>
			</div>

			<div class="form-group">
			    <?= $this->formLabel($abschluss) ?>
			    <?= $this->formElement($abschluss) ?>
			    <?= $this->formElementErrors()->render($abschluss, ['class' => 'help-block']) ?>
			    <small class="text-muted">Tragen Sie den Abschluss des aktuellen Studiengangs ein (z.B. Bachelor, Master oder Diplom).</small>
			</div>

			<div class="form-group">
			    <?= $this->formLabel($abschlussnote) ?>
			    <?= $this->formElement($abschlussnote) ?>
			    <?= $this->formElementErrors()->render($abschlussnote, ['class' => 'help-block']) ?>
			    <small class="text-muted">Abschlussnote oder aktueller Notendurchschnitt; falls ein abweichendes Notenschema verwendet wird, tragen Sie die Art des Abschlusses und Ihre Abschlussnote bzw. Ihren Notendurchschnitt bitte im Kommentarfeld unten ein.</small>
			</div>

			<div class="form-group" rows="24" cols="80">
			    <?= $this->formLabel($hinweise) ?>
			    <?= $this->formElement($hinweise) ?>
			    <?= $this->formElementErrors()->render($hinweise, ['class' => 'help-block']) ?>
			    <small class="text-muted">Bitte fügen Sie hier zusätzliche Mitteilungen ein, zum Beispiel, dass der Wert im Feld "Abschlussnote" nicht Ihre Abschlussnote, sondern Ihr aktueller Notendurchschnitt ist. Haben Sie Ihren Abschluss noch nicht erworben, tragen Sie hier bitte die Anzahl der zum Zeitpunkt der Bewerbung erworbenen ECTS-Kreditpunkte ein.</small>
			</div>
		</div>
	</div>
</div> <br>

<!--Einschätzung zur Zulassungsvoraussetzung -->

<div class="card-deck">
	<div class="card">
		<h3 class="card-header" style="font-weight:bold"><?= $this->escapeHtml($title4) ?></h3>
		<div class="card-body">	
			<?php
			$erreichteCredits = $form->get('erreichteCredits');
			$schwerpunktId = $form->get('schwerpunktId');
			?>
			<div class="form-group">
			    <?= $this->formLabel($erreichteCredits) ?>
			    <?= $this->formElement($erreichteCredits) ?>
			    <?= $this->formElementErrors()->render($erreichteCredits, ['class' => 'help-block']) ?>
			    <small class="text-muted">Im aktuellen Studiengang bisher erreichte ECTS-Anzahl.</small>
			</div>
			
			<div class="form-group">
			    <?= $this->formLabel($schwerpunktId) ?>
			    <?= $this->formElement($schwerpunktId) ?>
			    <?= $this->formElementErrors()->render($schwerpunktId, ['class' => 'help-block']) ?>
			    <small class="text-muted">Auswahl des Bachelor Schwerpunktes der Universität Regensburg, welcher als Basis für den Vergleich mit dem aktuellen Studiengang herangezogen wird, um die Zulassungsvoraussetzungen zu erfüllen.</small>
			</div>
			

		</div>
	</div>
</div> <br>

<!--Angaben zur Berufserfahrung-->
<div class="card-deck">
	<div class="card">
		<h3 class="card-header" style="font-weight:bold"><?= $this->escapeHtml($title5) ?></h3>
		<div class="card-body">	
			<?php
			$praktika = $form->get('praktika');
			$berufserfahrung = $form->get('berufserfahrung');
			?>
			<div class="form-group">
			    <?= $this->formLabel($praktika) ?>
			    <?= $this->formElement($praktika) ?>
			    <?= $this->formElementErrors()->render($praktika, ['class' => 'help-block']) ?>
			    <small class="text-muted">Bitte tragen Sie hier Ihre bisherigen Praktika ein. Machen Sie Angaben zu Unternehmen, Beschäftigungsdauer und Art der Tätigkeit.</small>
			</div>
			
			<div class="form-group">
			    <?= $this->formLabel($berufserfahrung) ?>
			    <?= $this->formElement($berufserfahrung) ?>
			    <?= $this->formElementErrors()->render($berufserfahrung, ['class' => 'help-block']) ?>
			    <small class="text-muted"> Bitte tragen Sie vorhandene Berufserfahrung bzw. eine abgeschlossene Berufsausbildung ein. Machen Sie Angaben zu Unternehmen, Beschäftigungsdauer und Art der Tätigkeit.</small>
			</div>
		</div>
	</div>
</div> <br>
<!--<a name="save" id="save" type="button" class="btn btn-primary hiddenButton" style="border: 1px solid transparent; padding: 0.375rem 0.75rem; line-height: 1.5; border-radius: 0.25rem; display: inline-block;" href="<?= $this->url('masterbewerbung', ['action' => 'zusammenfassung', 'idBewerbungscode' => $this->idBewerbungscode]) ?>">Daten speichern</a>-->
<?php
if(!$this->abgeschickt):
echo $this->formSubmit($submit);
endif;
echo $this->form()->closeTag();
?>
