<?php
$title = 'Master-Bewerbung - Fakultät für Wirtschaftswissenschaften';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1> <br>

<div class="card-deck">
	<div class="card">
		<h2 class="card-header">Current Announcements</h2>
		 <div class="card-body">
			If you have any questions regarding the application process, please first consult the <a href="https://www.uni-regensburg.de/wirtschaftswissenschaften/fakultaet/service/studienberatung/faqs/index.html#masterbewerbung">FAQ</a> and have a look at the <a href="<?= $this->url('tutorial', ['action' => 'index']) ?>">Tutorial</a>  <br></br>
			The Faculty's student advisors are also at your disposal  (<a href="mailto:studienberatung@wiwi.uni-regensburg.de">studienberatung@wiwi.uni-regensburg.de</a>). <br></br>
			Consultancy for the Master's programmes in Business Administration, (International) Economics, Business Information Systems, Real Estate Management:
Mr. Markus Lang
		   </br> 
			Telefonnummer: 0941-943-2747 <br>
		</div>
		<div class="alert alert-warning">
		Please refrain from asking about the processing status of your application. You will automatically be notified by e-mail when your application and the PDF summary have been received. Unfortunately, it is not possible to provide information about documents already received in advance.
		</div>
	</div>
</div><br> <br>

<div class="card-deck">
	<div class="card">
		 <div class="card-body">			
			Between 01.05.2021 and 01.06.2021 you can apply on this page for the Master's programmes starting in the winter semester 2018/19. The application deadline is 24.06.2020 (deadline).<br> <br>
			
			For your application, you need the following documents in electronic form: a certificate of completion of a course of study qualifying for the Master's degree (or an overview of grades if you have not yet completed your studies), a letter of motivation (only for the Master's course in Real Estate Management) and a curriculum vitae with supporting documents. You can then upload these documents on this page.<br> <br>
			
			Important: It is not necessary that you send the application documents in paper form to the dean's office. It is sufficient to print out the summary of the application, sign it and send it to the dean's office.<br> <br>
			
			If you have any questions regarding your application, please contact the Academic Advisory Service of the Faculty of Economic Sciencest  (<a href="mailto:studienberatung@wiwi.uni-regensburg.de">studienberatung@wiwi.uni-regensburg.de</a>) <br> <br>

			Please do not inquire about the processing status of your application. We will send your application as soon as possible by post.

		</div>
	</div>
</div> <br>





   





